### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by thunpisit** [kirankunigiri/peertalk-simple#1] opened 2017-05-23 05:23 UTC
Hello, When I ran the macOS part it works fine but there're crash on iOS app.

fatal error: unexpectedly found nil while unwrapping an Optional value
2017-05-22 22:22:31.299171-0700 PTSimpleiOS[1794:523791] fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) 
<img width="1177" alt="screen shot 2017-05-22 at 10 23 22 pm" src="https://cloud.githubusercontent.com/assets/3394671/26339516/49ed217e-3f3d-11e7-93dd-a388d5e702f6.png">
<img width="1142" alt="screen shot 2017-05-22 at 10 24 45 pm" src="https://cloud.githubusercontent.com/assets/3394671/26339545/8173abae-3f3d-11e7-8fe0-5e270de001bc.png">

**Comment by kirankunigiri** [comment] 2017-05-28 03:30
Hi! What version of Xcode are you using? I don't have any of the Swift Compiler Warnings that you have, and the bug doesn't occur on my devices. I'm using the latest version (Xcode 8.3.2).

**Comment by thunpisit** [comment] 2017-06-07 03:29
@kirankunigiri Hello so I ran your app on Simulator and it works fine but when I run it on my iPhone like physical iPhone it crashed when I click add. My Xcode is 8.3.3 right now and my iPhone is 10.3.2

**Comment by ninyawee** [comment] 2017-06-07 06:30
It happens to me when my mac is running duet display. @thunpisit

**Comment by thunpisit** [comment] 2017-06-07 08:23
@wasdee so how do you fixed the problem? Quiz the app or delete it?

**Comment by kirankunigiri** [comment] 2017-06-07 23:11
@wasdee does it work for you when you are not running Duet Display?
@thunpisit does the mac app crash too or is it just the iOS app?
This is hard for me to debug since I cannot replicate the bug at all. Can you give me more details such as iOS and macOS versions?
I also added a small update that fixes the warnings. This should not have any effect on performance, but you might want to run it again with the updated version and see if the bug still occurs.

**Comment by ninyawee** [comment] 2017-06-08 03:14
It does work smooth and correctly when the Duet is not running.
1000% no error.

if you want to reproduce i think just `brew cask install duet`

My guess on cause of this error is that a program is using the same port as this app over usbmux.

@kirankunigiri

**Comment by kirankunigiri** [comment] 2017-06-08 07:36
@thunpisit do you have any programs running that use USB connections?
@wasdee the port number is located in the Helper.swift file. Does changing it there fix it?

**Comment by thunpisit** [comment] 2017-06-08 19:39
Yeah exiting the Desktop Duet display solved the problem and @kirankunigiri Don't forget to add privacy into your info.plist for access photo library on iOS.

**Comment by thunpisit** [comment] 2017-06-11 09:39
@kirankunigiri One more quick question. So I drag your files (peertalk directory, Helper.swift, PTManager.swift, and PeertalkSimple-Bridging-Header) into my project folder and then when it build it gave me these errors. It doesn't happen in your sample project. Do you have any idea what happen?

<img width="1152" alt="screen shot 2017-06-11 at 2 39 29 am" src="https://user-images.githubusercontent.com/3394671/27009959-356569f2-4e4f-11e7-9752-a508b38adc96.png">

**Comment by kirankunigiri** [comment] 2017-06-19 19:34
In addition to just exiting Duet, changing the port number should also work. I'll close the issue if there are no other problems with this.

**Closed as completed** 2017-06-26 16:15 UTC
